import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full h-auto px-4 bg-gray-800">
          {/* una barra de navegación con tailwindcss */}
          <nav className="relative h-auto flex justify-end">
            <ul className=" flex h-auto">
              <li>
                <a href="/" className="text-white">
                  Home
                </a>
              </li>
              <span className="text-white mx-4"> | </span>
              <li>
                <a href="/store" className="text-white">
                  Store
                </a>
              </li>
            </ul>
          </nav>
          {/* <nav>
            <ul className=" ">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/store">Store</a>
              </li>
            </ul>
          </nav> */}
        </header>
        {children}
        </body>
    </html>
  );
}
